# .coderabbit.yaml
# Configuring CodeRabbit to use Conventional Comments format for code reviews

# General review guidelines
general_guidelines: |
  - Follow the Conventional Comments format for all review comments.
  - Use labels such as Praise, Suggestion, Issue, Question, Nitpick, Chore, or Thought.
  - Ensure comments are clear, constructive, and specific, providing context or examples where applicable.
  - For non-blocking comments, append (non-blocking) to the label.
  - For blocking comments requiring changes, append (blocking) to the label.
  - Example: "Suggestion (non-blocking): Consider renaming `var1` to `userCount` for clarity."
